// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20181113185619_changePhoneRequiring")]
    partial class changePhoneRequiring
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.ExtendedModels.CountryExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MobCode");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CountryExtended");
                });

            modelBuilder.Entity("Entities.ExtendedModels.PostBlogExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfCreation");

                    b.Property<string>("Name");

                    b.Property<string>("Plot");

                    b.Property<int>("TripId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("PostBlogExtended");
                });

            modelBuilder.Entity("Entities.ExtendedModels.RoleExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RoleExtended");
                });

            modelBuilder.Entity("Entities.ExtendedModels.TagExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("TagExtended");
                });

            modelBuilder.Entity("Entities.ExtendedModels.TripExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDone");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TripExtended");
                });

            modelBuilder.Entity("Entities.ExtendedModels.UserExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId");

                    b.Property<DateTime?>("DateOfBirth");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Phone");

                    b.Property<int>("RoleId");

                    b.Property<int?>("UserImageId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserImageId");

                    b.ToTable("UserExtended");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("userid");

                    b.Property<int>("TripId")
                        .HasColumnName("TripId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("Content");

                    b.HasKey("UserId", "TripId")
                        .HasName("pk_constraint_comment");

                    b.HasIndex("TripId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Entities.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MobCode")
                        .IsRequired()
                        .HasColumnName("mobilecode")
                        .HasMaxLength(5);

                    b.Property<string>("Name");

                    b.HasKey("Id")
                        .HasName("pk_constraint_country");

                    b.HasAlternateKey("MobCode")
                        .HasName("uq_constraint_mobcode_country");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Entities.Models.CountryPostBlog", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnName("countryid");

                    b.Property<int>("PostBlogId")
                        .HasColumnName("tripid");

                    b.HasKey("CountryId", "PostBlogId");

                    b.HasIndex("PostBlogId");

                    b.ToTable("CountryPostBlog");
                });

            modelBuilder.Entity("Entities.Models.CountryTrip", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnName("countryid");

                    b.Property<int>("TripId")
                        .HasColumnName("tripid");

                    b.HasKey("CountryId", "TripId");

                    b.HasIndex("TripId");

                    b.ToTable("CountryTrip");
                });

            modelBuilder.Entity("Entities.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("pk_constraint_Currency");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("Entities.Models.CurrencyExtended", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CurrencyExtended");
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnName("Path");

                    b.Property<int>("PostBlogId");

                    b.HasKey("Id")
                        .HasName("pk_constraint_image");

                    b.HasIndex("PostBlogId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Entities.Models.PostBlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnName("creationdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("namepostblog")
                        .HasMaxLength(100);

                    b.Property<string>("Plot")
                        .IsRequired()
                        .HasColumnName("plot");

                    b.Property<int>("TripId")
                        .HasColumnName("tripid");

                    b.HasKey("Id")
                        .HasName("pk_constraint_postblog");

                    b.HasIndex("TripId");

                    b.ToTable("PostBlog");
                });

            modelBuilder.Entity("Entities.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountSpent")
                        .HasColumnName("amountspent");

                    b.Property<int>("CurrencyId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description");

                    b.Property<int>("PostBlogId");

                    b.HasKey("Id")
                        .HasName("pk_constraint_purchase");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PostBlogId");

                    b.ToTable("Purchase");
                });

            modelBuilder.Entity("Entities.Models.Rating", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("userid");

                    b.Property<int>("TripId")
                        .HasColumnName("tripid");

                    b.Property<bool?>("RatingPostBlog")
                        .HasColumnName("ratingpostblog");

                    b.HasKey("UserId", "TripId")
                        .HasName("pk_constraint_rating");

                    b.HasIndex("TripId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("rolename")
                        .HasDefaultValue("User");

                    b.HasKey("Id")
                        .HasName("pk_constraint_role");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Entities.Models.Subscription", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("userid");

                    b.Property<int>("SubcriberId")
                        .HasColumnName("subscriberid");

                    b.HasKey("UserId", "SubcriberId")
                        .HasName("pk_constraint_subscription");

                    b.HasIndex("SubcriberId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("Entities.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("tagname")
                        .HasMaxLength(20);

                    b.HasKey("Id")
                        .HasName("pk_constraint_tag");

                    b.HasAlternateKey("Name")
                        .HasName("uq_constraint_tag");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Entities.Models.TagPostBlog", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnName("tagid");

                    b.Property<int>("PostBlogId")
                        .HasColumnName("postblogid");

                    b.HasKey("TagId", "PostBlogId")
                        .HasName("pk_constraint_tagpostblog");

                    b.HasIndex("PostBlogId");

                    b.ToTable("TagPostBlog");
                });

            modelBuilder.Entity("Entities.Models.TagTrip", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnName("tagid");

                    b.Property<int>("TripId")
                        .HasColumnName("tripid");

                    b.HasKey("TagId", "TripId")
                        .HasName("pk_constraint_tagtrip");

                    b.HasIndex("TripId");

                    b.ToTable("TagTrip");
                });

            modelBuilder.Entity("Entities.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDone")
                        .HasColumnName("isDone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("postname");

                    b.Property<int>("UserId");

                    b.HasKey("Id")
                        .HasName("pk_constraint_trip");

                    b.HasAlternateKey("Name")
                        .HasName("uq_constraint_trip");

                    b.HasIndex("UserId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryId")
                        .HasColumnName("country_id");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnName("dateofbirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(40);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnName("firstname")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnName("lastname")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(10);

                    b.Property<int>("RoleId")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_constraint_user");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("user_email_unique");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasName("user_phone_unique")
                        .HasFilter("[phone] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Entities.Models.UserImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnName("Path");

                    b.Property<int>("UserId")
                        .HasColumnName("userid");

                    b.HasKey("Id")
                        .HasName("pk_constraint_userimage");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserImage");
                });

            modelBuilder.Entity("Entities.ExtendedModels.PostBlogExtended", b =>
                {
                    b.HasOne("Entities.ExtendedModels.TripExtended", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.ExtendedModels.TripExtended", b =>
                {
                    b.HasOne("Entities.ExtendedModels.UserExtended", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.ExtendedModels.UserExtended", b =>
                {
                    b.HasOne("Entities.ExtendedModels.CountryExtended", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Entities.ExtendedModels.RoleExtended", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.Models.UserImage", "UserImage")
                        .WithMany()
                        .HasForeignKey("UserImageId");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.ExtendedModels.TripExtended", "Trip")
                        .WithMany("Comments")
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_constraint_TripId_comment")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.UserExtended", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_constraint_userid_comment")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Entities.Models.CountryPostBlog", b =>
                {
                    b.HasOne("Entities.ExtendedModels.CountryExtended", "Country")
                        .WithMany("CountryPostBlogs")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_constraint_countryid_countrypostblog")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.PostBlogExtended", "PostBlog")
                        .WithMany("CountryPostBlogs")
                        .HasForeignKey("PostBlogId")
                        .HasConstraintName("fk_constraint_postblogid_countrypostblog")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.CountryTrip", b =>
                {
                    b.HasOne("Entities.ExtendedModels.CountryExtended", "Country")
                        .WithMany("CountryTrips")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_constraint_countryid_countrytrip")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.TripExtended", "Trip")
                        .WithMany("CountryTrips")
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_constraint_tripid_countrytrip")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Image", b =>
                {
                    b.HasOne("Entities.ExtendedModels.PostBlogExtended", "PostBlog")
                        .WithMany("Images")
                        .HasForeignKey("PostBlogId")
                        .HasConstraintName("fk_constraint_postblogid_image")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.PostBlog", b =>
                {
                    b.HasOne("Entities.ExtendedModels.TripExtended", "Trip")
                        .WithMany("PostBlogs")
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_constraint_postblog")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Purchase", b =>
                {
                    b.HasOne("Entities.Models.CurrencyExtended", "Currency")
                        .WithMany("Purchases")
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("fk_constraint_purchase_currencyid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.PostBlogExtended", "PostBlog")
                        .WithMany("Purchases")
                        .HasForeignKey("PostBlogId")
                        .HasConstraintName("fk_constraint_purchase_postblogid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Rating", b =>
                {
                    b.HasOne("Entities.ExtendedModels.TripExtended", "Trip")
                        .WithMany("Ratings")
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_constraint_tripid_rating")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.UserExtended", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_constraint_userid_rating")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Entities.Models.Subscription", b =>
                {
                    b.HasOne("Entities.ExtendedModels.UserExtended", "SubscriberIdNavidgation")
                        .WithMany("RelationWithSubscriberIdNavigation")
                        .HasForeignKey("SubcriberId")
                        .HasConstraintName("fk_constraint_subscriberid_subscription")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.UserExtended", "UserIdNavigation")
                        .WithMany("RelationWithUserIdNavigation")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_constraint_userid_subscription")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Entities.Models.TagPostBlog", b =>
                {
                    b.HasOne("Entities.ExtendedModels.PostBlogExtended", "PostBlog")
                        .WithMany("TagPostBlogs")
                        .HasForeignKey("PostBlogId")
                        .HasConstraintName("fk_constraint_postblogid_tagpostblog")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.TagExtended", "Tag")
                        .WithMany("TagPostBlogs")
                        .HasForeignKey("TagId")
                        .HasConstraintName("fk_constraint_tagid_tagpostblog")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.TagTrip", b =>
                {
                    b.HasOne("Entities.ExtendedModels.TagExtended", "Tag")
                        .WithMany("TagTrips")
                        .HasForeignKey("TagId")
                        .HasConstraintName("fk_constraint_tagid_tagtrip")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Entities.ExtendedModels.TripExtended", "Post")
                        .WithMany("TagTrips")
                        .HasForeignKey("TripId")
                        .HasConstraintName("fk_constraint_tripid_tagtrip")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.Trip", b =>
                {
                    b.HasOne("Entities.ExtendedModels.UserExtended", "User")
                        .WithMany("Trips")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_userid_trip")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.HasOne("Entities.ExtendedModels.CountryExtended", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .HasConstraintName("fk_constraint_country_user")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Entities.ExtendedModels.RoleExtended", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("fk_constraint_role_user")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Entities.Models.UserImage", b =>
                {
                    b.HasOne("Entities.Models.User", "User")
                        .WithOne("UserImage")
                        .HasForeignKey("Entities.Models.UserImage", "UserId")
                        .HasConstraintName("fk_constraint_userid_userimage")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
